### PR TITLE
SpineObject persistence update.

### PR DESCRIPTION
**Pull request by mtannel**
Try to give at least a little support for reading/writing as taml.  Also a bug fix and couple of other minor tweaks.

### CODE REVIEW

**Comment by mtannel** [comment]
Hi greenfire,
A couple of updates to address some things I missed the first time around.  Let me know if you have any questions.  Also, if any bugs come up, let me know and I'll try and take a look into it.  The code is pretty green, so I suspect some might be lurking in there.
Cheers,
Mike

**Comment by mtannel** [comment]
btw - Thanks for the invite to Discord.  To get an account I need to send a picture of me holding my drivers license, all big enough so they can see its contents (alternatively the left foot of my first born child).  Whatever about that.  Apparently being born in 1971 triggered some kind of profiling filter.

**Comment by greenfire27** [comment]
I suppose they don't get many users over the age of 40 or something. I would just send the foot. 

But seriously thanks for the help. Spine needed some love. I'll let you know if I have any questions. I don't think I'll be able to review the code until tomorrow.

**Comment by mtannel** [comment]
You're right - pulled that out.

**Pull request merged**
