### PR TITLE
Updated Spine runtime version to 3.8. 

### PR DESCRIPTION
**Pull request by mtannel**
Also refactored from SkeletonObject to SpineObject to clear way for other potential runtimes like Creature or Flare. I don't know if/when I would get to that.  

Anyway, I had some fun with this and I hope it can be useful.

### CODE REVIEW

**Comment by greenfire27** [comment]
Thanks for contributing! Can you explain your changes to the batch renderer? I just need to understand what's going on there and I'll merge the pull request.

**Comment by mtannel** [comment]
Sure - The change there was to provide support for per-vertex color assignment in the SubmitTriangles method.  Instead of a single ColorF, it now wants an array.  It's used by the special effect code (the swirl and jitter stuff) which messes with the color assigned at each vertex.   SubmitTriangles is used to render the mesh attachments which consist of more than four points.   It's more general than SubmitQuad and I used it to render everything, even the region attachments which could have been processed by SubmitQuad.

**Comment by greenfire27** [comment]
Thanks! I've had plans to do something similar to allow spites to define a color for each corner (vertex) instead of a single color for the whole sprite. Seems you've done half the work for me.

**Comment by marauder2k7** [comment]
hey mtannel join us on discord, would be interesting to get your input on a few of the ideas we have for future updates to Torque 2d :) https://discord.com/invite/qdAZxT4

**Comment by mtannel** [comment]
Tried going over to Discord, but it didn't let me past the birthday screen.   Looks like I'll need to create and verify an account to get in.

**Pull request merged**
