### PR TITLE
Fix potential NULL dereference

### PR DESCRIPTION
**Pull request by mjunix**

### CODE REVIEW

**Comment by greenfire27** [comment]
So what you wrote seems correct, but the whole thing is wrapped in if(pLoadedEntry == null) 

So it seems like it would still crash if this code were to run since the last parameter uses pLoadedEntry. Since this is just a warning we should be safe in pulling that out and rewording the message a little.

**Comment by mjunix** [comment]
Ah yes, you're right, I missed the second dereference of pLoadedEntry. You probably know how to fix it better than me.

**Comment by dottools** [comment]
Just commenting on this PR instead of on all of the pull requests.

Next time you can just make a single branch and pull request for ALL these 15 past pull requests. It is completely unnecessary do so many pull requests for few code linear changes when it literally could have been just one pull request for these bug fix patch set of changes. Especially when each PR has no descriptions and not useful subjects. Now the commit history into development branch for today looks god awful and is not helpful.

**Comment by greenfire27** [comment]
I agree with dottools, although I'm less worried about the history. It would have been faster for me to review a single pull request with 15 changes. My time is at a premium these days.

However, I'd also like to thank you for making these changes and taking the time to get them pulled into the engine. We need more community involvement like this and I'd rather have to deal with a dozen pull requests than no pull requests at all. Thanks!

**Pull request merged**
